# Generated by Django 5.1 on 2025-03-27 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('PostImage', models.ImageField(upload_to='uploads/')),
                ('buttonColor', models.CharField(max_length=7)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('lifestyle', 'Lifestyle')], default='tech', max_length=20)),
                ('priority', models.CharField(choices=[('BiggerPics', 'BiggerPics'), ('Normal', 'Normal'), ('FooterPics', 'FooterPics')], default='Normal', max_length=20)),
                ('Description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
