# Generated by Django 5.1 on 2025-05-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_datapost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapost',
            name='nicknames',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
