# Generated by Django 5.1 on 2025-07-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_datapost_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapost',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('fashion', 'Fashion'), ('lifestyle', 'Lifestyle'), ('health', 'Health'), ('bussiness', 'Bussiness')], default='tech', max_length=20),
        ),
    ]
