# Generated by Django 5.1 on 2025-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_datapost_slug_alter_datapost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
