# Generated by Django 5.1 on 2025-07-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0005_alter_datapost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
