# Generated by Django 5.1 on 2025-07-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slugs',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
